services:
  app:
    build: .
    container_name: legal-docs-app
    volumes:
      - .:/app
    depends_on:
      - db

    env_file:
      - .env.docker
      - .env.test

    # environment:
    # DATABASE_URL: postgres://johannes:johannes@db:5432/legal_docs_db
    # APP_ENV: docker
    # DATABASE_NAME: legal_docs_db
    # DATABASE_USER: johannes
    # DATABASE_PASSWORD: johannes
    # DATABASE_HOST: db
    # DATABASE_PORT: 5432
    tty: true

  db:
    image: postgres:15
    container_name: legal-docs-db
    environment:
      POSTGRES_USER: johannes
      POSTGRES_PASSWORD: johannes
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
    driver: local
